# Generated by Django 3.2.8 on 2021-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Parametro')),
                ('valor', models.CharField(max_length=512, verbose_name='Valor do Parametro')),
            ],
            options={
                'db_table': 'Parametros_Server',
            },
        ),
    ]
