# Generated by Django 3.2.8 on 2021-11-22 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=150, verbose_name='Nome')),
            ],
            options={
                'db_table': 'gerencia',
            },
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Macro', max_length=150, verbose_name='Nome do Macro')),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('P', 'Publicado')], max_length=1)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processo.gerencia')),
            ],
            options={
                'db_table': 'macro',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Processo', max_length=150, verbose_name='Nome do Processo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do Processo')),
                ('data', models.DateField(auto_now_add=True)),
                ('processo', models.FileField(upload_to='processo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('status', models.CharField(choices=[('C', 'Cadastrado'), ('P', 'Publicado')], max_length=1)),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processo.macro')),
            ],
            options={
                'db_table': 'processo',
            },
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processo.processo')),
            ],
        ),
    ]
